def test(**kwargs):
    '''
    Test 012: Can we load the synthetic CCDataSet
        generated by calcom.utils.synthetic_datasets.generate_synthetic_ccd2()?
    '''

    try:
        import calcom
        ccd = calcom.utils.synthetic_datasets.generate_synthetic_ccd2()
        result = True
    except:
        result = False
    #

    return result
#

if __name__=="__main__":
    print( test() )
